# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Random Thoughts
email: killogge@gmail.com
repository: muraj/muraj.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github_username: muraj
minimal_mistakes_skin: "dark"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Cory Perry"
  avatar : "https://gravatar.com/avatar/39a4e7d053e8b405ab1673eae9a9b31abfcd797a3888b63a1e107cd6d2b91728?size=128"
  bio    : "Software Developer with crazy ideas and interests."
  links:
    - label: "Sunnyvale, CA"
      icon: "fas fa-fw fa-map-marker-alt"
    - label: "Random Thoughts"
      icon: "fas fa-fw fa-link"
      url: "https://muraj.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/muraj"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/coryperr"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/cory.r.perry"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discordapp.com/users/387041126282035201"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/muraj"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/coryperr"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/cory.r.perry"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discordapp.com/users/387041126282035201"

comments:
  provider: "giscus"
  giscus:
    repo_id              : R_kgDOK0L-pw # Shown during giscus setup at https://giscus.app
    category_name        : Blog Comments # Full text name of the category
    category_id          : DIC_kwDOK0L-p84CbaWP # Shown during giscus setup at https://giscus.app
    discussion_term      : pathname # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : 1 # '1' for enabled (default), '0' for disabled
    theme                : dark_dimmed # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
